import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

export const metadata: Metadata = {
  title: "Multi Tenant ECommerce",
  description: "Generated by create next app",
};
const dmSans = DM_Sans({subsets:['latin'],weight:['700']})
const RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>) =>{
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.className} antialiased`}>
        <NuqsAdapter>
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
export default RootLayout;