import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Multi Tenant ECommerce",
  description: "Generated by create next app",
};
const dmSans = DM_Sans({subsets:['latin'],weight:['700']})
const RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>) =>{
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
export default RootLayout;